/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "OpenCV-4.9.0-android-sdk/sdk/native/jni/include/opencv2/core/core.hpp"
#include "OpenCV-4.9.0-android-sdk/sdk/native/jni/include/opencv2/imgproc/imgproc.hpp"
/* Header for class com_flycatcher_smartsketcher_util_JniBridge */

#ifndef _Included_com_flycatcher_smartsketcher_util_JniBridge
#define _Included_com_flycatcher_smartsketcher_util_JniBridge
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_com_flycatcher_smartstring_JniBridge
 * Method:    showText
 */
JNIEXPORT jstring JNICALL Java_com_flycatcher_smartstring_JniBridge_showText
        (JNIEnv *, jobject thiz, jstring text);

/*
 * Class:     Java_com_flycatcher_smartstring_JniBridge
 * Method:    greyImage
 */
JNIEXPORT void JNICALL Java_com_flycatcher_smartstring_JniBridge_greyImage
        (JNIEnv *, jobject, jint, jint, jintArray, jintArray);


#ifdef __cplusplus
}
#endif
#endif
